# Default values for mariadb-for-k3s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: mariadb
  tag: ""

service:
  type: ClusterIP
  port: 3306

resources: {}

mariadb:
  rootPasswd: "!Q@W3e4r"

