apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mariadb-for-k3s.fullname" . }}-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
